### PR TITLE
[#151004135] Create paas submit app

### PR DESCRIPTION
**Pull request by chrisfarms**
## What

We want to allow potential tenants to signup and existing tenants to contact support via forms on our product page.

This `paas-submit` app renders HTML forms that can be embeded using iframes into the product page and writes the results into Deskpro on submit.

More info in the [README](https://github.com/alphagov/paas-submit/blob/7ea33791dd656e9500a2436671a7e5d98d3a9f59/README.md) and by viewing the index page of the running app.

## Notes

* It's a ruby/sinatra app as it may be handed to a more front-endy developer in the future.
* The form itself is pretty simple right now, a future story is responsible for ensuring the fields are relevent. 

## How to review

You can deploy to your dev environment by modifying the manifest.yml to include the required `DESKPRO_*` environment variables or run locally using:

```
DESKPRO_TEAM_ID=1 DESKPRO_API_KEY=REDACTED DESKPRO_ENDPOINT=REDACTED make dev`
```

* The index page of the app will show the HTML snippets required for embedding.
* The /support form should create tickets in deskpro assigned to the correct team
* The /register form should create tickets in deskpro assigned to the correct team
* Ensure basic form styling and validation works
* You should be able to clearly see how you might extend the forms with more fields 
* The embed snippets on the `/` page should work as expected
* Successful submissions should generate real-time events in google analytics. (I created an account to test on the `/` page ... you could signup for a GA account and switch out the code to test it out).

## Who can review

Not @chrisfarms nor @henrytk

### CODE REVIEW

**Comment by 46bit** [comment]
I like what you've built!

I tried to embed the iframes in a separate website and got an error in Chrome's developer console: `Refused to display 'http://localhost:9292/register' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

Sinatra has built-in protection against XSS, part of which involves returning the [`X-Frame-Options: SAMEORIGIN` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) to prevent embedding it in `iframes` on other websites. 

I found [a StackOverflow post that suggests how to disable this](https://stackoverflow.com/questions/7840613/how-do-i-get-sinatra-to-refrain-from-adding-the-x-frame-options-header). In time we may want to whitelist the particular deployed apps that use these forms, but for now we might just want to disable the protection entirely.

Thoughts?

**Comment by chrisfarms** [comment]
🙌  disabled the "protection" ... a whitelist in future would be good idea.

**Comment by 46bit** [comment]
@chrisfarms It doesn't look like your change took effect. I got things to work by changing `config.ru` to do:

```ruby
require './app'
class App
    configure do
        set :server, :puma
        set :protection, :except => :frame_options
    end
end
run App
```

I think it might be cleaner to take the application out of `App` than to do that.

I think it a test checking this header isn't set would be a good idea as well.

**Comment by chrisfarms** [comment]
Okay found the issue, I was confused by the loading order of sinatra base vs the app itself 😖 

...should be sorted now and added test.

**Comment by 46bit** [comment]
Fabulous 👍

**Comment by 46bit** [comment]
Out of interest, what was the problem with loading order? Is it that `App` extends `Sinatra::Base` in a separate import to that in `config.ru`, or similar?

**Pull request merged**
